// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTVU3m8vYFHggV5x6AWcjyMpHXUh66CA',
    appId: '1:306145407301:web:b289c5c0b279bb59a88e2c',
    messagingSenderId: '306145407301',
    projectId: 'conjunto-app-1688d',
    authDomain: 'conjunto-app-1688d.firebaseapp.com',
    storageBucket: 'conjunto-app-1688d.firebasestorage.app',
    measurementId: 'G-V0ESL2GXKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDko9gq4M-MfKOASt6xDiexrce-S05VqFQ',
    appId: '1:306145407301:android:0351eb1c29268704a88e2c',
    messagingSenderId: '306145407301',
    projectId: 'conjunto-app-1688d',
    storageBucket: 'conjunto-app-1688d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOaCjIba6OIYdjnSPraZCdjdF25vOf_Vk',
    appId: '1:306145407301:ios:c7a1ed0bb7de74f1a88e2c',
    messagingSenderId: '306145407301',
    projectId: 'conjunto-app-1688d',
    storageBucket: 'conjunto-app-1688d.firebasestorage.app',
    iosBundleId: 'com.example.conjuntoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOaCjIba6OIYdjnSPraZCdjdF25vOf_Vk',
    appId: '1:306145407301:ios:c7a1ed0bb7de74f1a88e2c',
    messagingSenderId: '306145407301',
    projectId: 'conjunto-app-1688d',
    storageBucket: 'conjunto-app-1688d.firebasestorage.app',
    iosBundleId: 'com.example.conjuntoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsTVU3m8vYFHggV5x6AWcjyMpHXUh66CA',
    appId: '1:306145407301:web:fd2fdd44fa8c1400a88e2c',
    messagingSenderId: '306145407301',
    projectId: 'conjunto-app-1688d',
    authDomain: 'conjunto-app-1688d.firebaseapp.com',
    storageBucket: 'conjunto-app-1688d.firebasestorage.app',
    measurementId: 'G-1881VEW8J0',
  );
}
